db:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: Qwerty@12345
      
  ports:
    - "3306:3306"
  volumes:
   - /root/Java-Mysql-Simple-Login-Web-application/mysql/sample.sql:/docker-entrypoint-initdb.d/sample.sql
   - /sql:/var/lib/mysql
   - /tmp/Java-Mysql-Simple-Login-Web-application/dockerdemo.txt:/tmp/dockerdemo.txt
web:
  build: ./
  ports:
   - "8081:8080"
#  volumes:
#   - /tmp/Java-Mysql-Simple-Login-Web-application/dockerdemo.txt:/usr/local/tomcat/dockerdemo.txt
  links:
   - db

